import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/navbar/Navbar.component";
import Container from "@/components/common/container/Container.component";
import RootProvider from "@/providers/RootProvider";
import { ClerkProvider } from "@clerk/nextjs";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Next Store App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${geistMono.className} antialiased`}>
          <RootProvider>
            <Navbar />
            <Container className="py-20">{children}</Container>
          </RootProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
